# Generated by Django 2.2.3 on 2019-07-28 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('month', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Útima atualização')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_seller', to='seller.Seller')),
            ],
        ),
    ]
