# Generated by Django 2.2.3 on 2019-07-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='min_value',
            field=models.FloatField(),
        ),
    ]
