# Generated by Django 2.2.3 on 2019-07-09 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('street', models.CharField(max_length=200)),
                ('neighborhood', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='seller.Seller')),
            ],
        ),
    ]
