# Generated by Django 2.2.3 on 2019-07-28 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='year',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
